name: "Collect IPs"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.2'

- name: Run PHP code
  shell: php {0}
  run: |
    index.php
